import {OpenAI} from "openai";

const openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY,
});

type ConversationMessage = {
    role: "user" | "assistant";
    content: string;
};

/**
 *
 * @param question
 * @param context
 */
export async function generateAnswer(
    question: string,
    context: string,
    conversationHistory: ConversationMessage[] = []
): Promise<string> {

    //uses "as const" to tell TypeScript that role is specifically the literal value in the "",
    // instead of treating it as a generic string.
    const messages = [
        {
            role: "system" as const,
            content: `
            You are a study assistant. Answer the student's current question using only the provided study-material context.

            Previous conversation messages are provided only to help you understand what the student is referring to. Do not treat claims from previous conversation messages as study-material evidence.

            If the study-material context does not contain sufficient information to answer the question, say so. Do not guess.

            Do not mention "the provided context" in the answer.

            Format responses using Markdown.

            Formatting rules:
            - Use short paragraphs and bullet points when appropriate.
            - Use bold text for important terms.
            - ALL mathematical notation must use LaTeX math delimiters.
            - For inline mathematics, ALWAYS use $...$.
            - For equations on their own line, ALWAYS use $$...$$.
            - Never use \$begin:math:text$ \\$end:math:text$, \$begin:math:display$ \\$end:math:display$, or plain parentheses as LaTeX delimiters.
            - Do not write LaTeX commands such as \\mid, \\sum, or \\frac outside $...$ or $$...$$.
            - Keep displayed equations concise to avoid unnecessary horizontal overflow.
            - Avoid large walls of text.
        `.trim(),
        },

        ...conversationHistory,

        {
            role: "user" as const,
            content: `
Study-material context:
${context}

Current question:
${question}
        `.trim(),
        },
    ];

    //send request to OpenAI
    const response = await openai.chat.completions.create({
        model: "gpt-4.1-mini",
        messages: messages,
    });


    //return the answer generated by AI that is stored in response
    const answer = response.choices[0].message.content;

    //return answer generated or return given string if answer was null
    return answer ?? "I could not generate an answer.";
}